app:
  name: "Hexagonal Architecture, Domain Driven Design (DDD), Test Driven Design (TDD), RESTful, gRPC, Swagger, Gorm(PostgreSQL), Notification(Twilio), RabbitMQ, Prometheus, Grafana, Jaeger and Gin in Golang"
  debug: "true"
  env: "dev" # local, dev, prod, test
  log_level: "debug"
  version: "1.0.0"

server:
  host: "0.0.0.0"
  port: "3000"

db:
  host: "postgres" #for docker development
  #host: "localhost" #for local development
  port: "5432"
  test_port: "5433"
  username: "postgres"
  password: "postgres"
  name: "go-arch"

#It is separated from server configs maybe you want to use different host and port for swagger
#in different directory such as cmd/swagger
swagger:
  host: "0.0.0.0"
  port: "3000"
  path: "swagger/doc.json"


grpc:
  host: "0.0.0.0"
  port: "50051"


rabbitmq:
  default_exchange: "default_exchange"
  default_queue: "default_queue"
  username: "guest"
  password: "guest"
  port: "5672"
  test_port: "5673"
  docker_host: "rabbitmq" # for docker development
  local_host: "localhost" # for local development



