apiVersion: v1
kind: Secret
metadata:
  name: go-arch-secrets
  namespace: development
type: Opaque
stringData:
  APP_NAME: "Blog"
  VERSION: "1.0.0"
  IS_LOGGER: "true"
  SERVER_HOST: "0.0.0.0"
  SERVER_PORT: "8080"
  DB_HOST: "postgres"
  DB_USER: "postgres"
  DB_PASS: "postgres"
  DB_NAME: "go-arch"
  DB_PORT: "5432"
  DB_PORT_TEST: "5433"
  GRPC_HOST: "0.0.0.0"
  GRPC_PORT: "9090"
  SWAGGER_HOST: "localhost"
  SWAGGER_PORT: "8081"
  SWAGGER_PATH: "swagger/doc.json"
  TWILIO_ACCOUNT_SID: "xxx"
  TWILIO_AUTH_TOKEN: "xxx"
  TWILIO_PHONE_NUMBER: "xxx"
  TO_PHONE_NUMBER: "xxx"
