apiVersion: v1
kind: Service
metadata:
  name: go-arch
  namespace: development
spec:
  selector:
    app: go-arch
  ports:
    - name: http
      port: 8080
      targetPort: 3000
    - name: grpc
      port: 9090
      targetPort: 9090
  type: ClusterIP
